name: downloader
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  fluent_ui: ^4.11.3
  flutter_svg: ^2.0.10
  provider: ^6.1.2
  dio: ^5.4.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  mime: ^1.0.5
  file_picker: ^6.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  workmanager: ^0.5.2
  flutter_file_dialog: ^3.0.2
  url_launcher: ^6.2.5
  flutter_icons_null_safety: ^1.1.0
  http: ^1.2.0
  html: ^0.15.4
  receive_sharing_intent: ^1.4.5
  uni_links: ^0.5.1
  clipboard_watcher: ^0.2.0
  flutter_background_service: ^5.0.5
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

